{ config, pkgs, lib, ... }:

let
  cfg = config.programs.tmux;
  format = pkgs.formats.keyValue { };
in

{
  options.programs.tmux = {
    enable = lib.mkEnableOption "tmux terminal multiplexer";

    package = lib.mkPackageOption pkgs "tmux" { };

    prefix = lib.mkOption {
      type = lib.types.str;
      default = "C-b";
      description = "Prefix key combo used before all tmux commands.";
      example = "C-a";
    };

    baseIndex = lib.mkOption {
      type = lib.types.int;
      default = 0;
      description = "Starting index for windows and panes.";
    };

    mouse = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable mouse support (click to select pane, drag to resize/scroll).";
    };

    historyLimit = lib.mkOption {
      type = lib.types.int;
      default = 10000;
      description = "Number of lines of scrollback kept per pane.";
    };

    terminal = lib.mkOption {
      type = lib.types.str;
      default = "tmux-256color";
      description = "$TERM value tmux reports to programs running inside it.";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Raw tmux.conf lines appended after the generated settings.";
      example = ''
        set -g status-bg colour235
        bind r source-file ~/.tmux.conf \; display "Reloaded!"
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    environment.etc."tmux.conf".text = ''
      # Generated by NixOS
      set -g prefix ${cfg.prefix}
      unbind C-b
      bind ${cfg.prefix} send-prefix

      set -g base-index ${toString cfg.baseIndex}
      setw -g pane-base-index ${toString cfg.baseIndex}

      set -g mouse ${if cfg.mouse then "on" else "off"}
      set -g history-limit ${toString cfg.historyLimit}
      set -g default-terminal "${cfg.terminal}"

      ${cfg.extraConfig}
    '';
  };

  # -- Placeholder for future integration hooks --
  # Nothing wired up yet. Likely candidates: a tmux status-bar theme that
  # matches matugen/wallust colors, or session-restore via a plugin.
}
