{ config, pkgs, lib, ... }:

let
  cfg = config.programs.bat;
  format = pkgs.formats.toml { };
in

{
  options.programs.bat = {
    enable = lib.mkEnableOption "Bat cat replacement";
    
    package = lib.mkPackageOption pkgs "bat" { };
    
    theme = lib.mkOption {
      type = lib.types.str;
      default = "Catppuccin Mocha";
      description = "Theme";
    };
    
    paging = lib.mkOption {
      type = lib.types.str;
      default = "always";
      description = "Paging: always, never, auto";
    };
    
    italicText = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable italic text";
    };
    
    lineNumbers = lib.mkOption {
      type = lib.types.enum [ "true" "false" "auto" ];
      default = "auto";
      description = "Line numbers: true, false, auto";
    };
    
    style = lib.mkOption {
      type = lib.types.str;
      default = "auto";
      description = "Style: auto, plain, changes, header, grid, numbers";
    };
    
    aliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        cat = "bat -p";
        less = "bat";
      };
      description = "Shell aliases";
    };
    
    settings = lib.mkOption {
      type = format.type;
      default = { };
      description = "Bat configuration";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];
    
    environment.shellAliases = cfg.aliases;
    
    environment.etc."bat/config".text = lib.mkIf (cfg.settings != { }) ''
      # Generated by NixOS
      ${lib.concatStrings (lib.mapAttrsToList (k: v: "${k}=${toString v}\n") cfg.settings)}
    '';
    
    environment.etc."bat/config".text = ''
      # Generated by NixOS
      --theme="${cfg.theme}"
      --paging="${cfg.paging}"
      --italic-text=${if cfg.italicText then "always" else "never"}
      --line-numbers="${cfg.lineNumbers}"
      --style="${cfg.style}"
    '';
  };

  # -- Placeholder for future integration hooks --
  # Nothing wired up yet. Likely candidates: extraConfig passthrough,
  # or cross-module hooks (e.g. theme colors from matugen/wallust).
}
