{ pkgs, ... }:
{

  wayland.windowManager.hyprland = {
    enable = true;
  };

  xdg.configFile."hypr/hyprland.lua".text = ''
    -- OvrOS Hyprland config (native Lua, Hyprland 0.55+)

   hl.config({
      autogenerated = false, # Prevents the yellow warning bar
      general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,
      },
      decoration = {
        rounding = 8,
        active_opacity = 1.0,
        inactive_opacity = 0.95,
      },
      input = {
        kb_layout = "us",
        follow_mouse = 1,
      },
    })

    -- Autostart programs safely on system launch
    hl.on("hyprland.start", function()
      hl.exec_cmd("waybar")
      hl.exec_cmd("nm-applet --indicator")
      hl.exec_cmd("blueman-applet")
      hl.exec_cmd("${pkgs.hyprpolkitagent}/bin/hyprpolkitagent")
      hl.exec_cmd("swww-daemon")

      -- Mission Center + CoreCtrl: launched hidden in special workspaces
      hl.exec_cmd("[workspace special:sysmon silent] mission-center")
      hl.exec_cmd("[workspace special:gpu silent] corectrl")
    end)

    -- Core System Binds
    hl.bind("super + return", hl.dsp.exec("ghostty"))
    hl.bind("super + q", hl.dsp.killactive())
    hl.bind("super + e", hl.dsp.exec("ghostty -e yazi"))
    hl.bind("super + r", hl.dsp.exec("wofi --show drun"))
    hl.bind("super + c", hl.dsp.exec("hypr-live-config"))
    hl.bind("super + m", hl.dsp.exit())
    hl.bind("super + v", hl.dsp.togglefloating())
    hl.bind("super + f", hl.dsp.fullscreen())

    -- Utilities (Screenshot & Dictation require custom inline Lua functions)
    hl.bind("super + shift + s", function()
      hl.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -")
    end)
    hl.bind("super + space", function()
      hl.exec_cmd("nerd-dictation begin --simulate-input-tool=WTYPE || nerd-dictation end")
    end)

    -- Scratchpad toggles for the system/GPU monitors
    hl.bind("super + d", hl.dsp.togglespecialworkspace("sysmon"))
    hl.bind("super + shift + d", hl.dsp.togglespecialworkspace("gpu"))
  '';

  home.sessionVariables = {
    NIXOS_OZONE_WL = "1"; # Electron apps (Vesktop, OBS, etc.) use Wayland
  };
}