{ config, pkgs, lib, ... }:

let
  cfg = config.programs.htop;
in

{
  options.programs.htop = {
    enable = lib.mkEnableOption "htop interactive process viewer";
    
    package = lib.mkPackageOption pkgs "htop" { };
    
    settings = lib.mkOption {
      type = lib.types.attrs;
      default = { };
      description = "htop configuration settings";
      example = {
        hide_kernel_threads = true;
        hide_userland_threads = true;
        tree_view = false;
        highlight_changes = true;
        highlight_changes_delay = 1500;
      };
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];
    
    environment.etc."htoprc".text = lib.mkIf (cfg.settings != { }) ''
      # Generated by NixOS
      ${lib.concatStrings (lib.mapAttrsToList (k: v: "${k}=${toString v}\n") cfg.settings)}
    '';
  };

  # -- Placeholder for future integration hooks --
  # Nothing wired up yet. Likely candidates: extraConfig passthrough,
  # or cross-module hooks (e.g. theme colors from matugen/wallust).
}
